### ISSUE TITLE
Not an issue (how to output to csv)

### ISSUE THREAD

**Issue by robpot891** [ocelotsloth/nflscores#1]
Awesome project! I was wondering if you could tell me how I would write to a csv?
I've tinkered with "	w := csv.NewWriter(os.Stdout)" but can't get it to work.

**Comment by ocelotsloth** [comment]
Thanks! The next step for this is really to add a command line interface which lets you select a year, year/week and optionally specify a command line flag to write to. I wrote the existing code in just a couple hours so didn't go quite that far.

I'll revisit this in a bit to add a better interface.

**Comment by ocelotsloth** [comment]
Hey @robpot891 I think you'll find the new interface a bit more user-friendly. Give it a spin!

**Comment by robpot891** [comment]
Thanks a lot @ocelotsloth it works like a charm. Awesome tool
